### ISSUE TITLE
Merchant icon

### ISSUE THREAD

**Issue by HeavenlyDog** [game-icons/icons#812] opened 2021-03-17 14:12 UTC
Hello.
How is the game-icons.net community doing?
I am preparing an adventure board game, and I would need an icon representing a Merchant. It would be too much to ask?
Greetings from France.

**Comment by Delapouite** [comment] 2021-03-17 14:41
Hi. Duplicate of https://github.com/game-icons/icons/issues/812

**Closed by Delapouite** 2021-03-17 14:41 UTC
