### ISSUE TITLE
Badges with numerical values.

### ISSUE THREAD

**Issue by Mikey76500** [game-icons/icons#784] opened 2020-10-30 06:40 UTC
As nice as the Icon Badges that already exist are, there's no Badges that have only numbers in them. I'd be happy with just 1-10, myself. Thanks in advance. :)

**Comment by Delapouite** [comment] 2020-10-30 08:03
Hello. Yes they will come. Duplicate of https://github.com/game-icons/icons/issues/768

**Closed by Delapouite** 2020-10-30 08:03 UTC
